# Generated by Django 2.1 on 2018-08-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.EmailField(max_length=254)),
                ('name', models.TextField()),
                ('artifact_location', models.TextField()),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
