# Generated by Django 2.1 on 2018-08-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('value', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='account_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='qbol_user_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelparams',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_parameters', to='mlmodels.MLModel'),
        ),
    ]
