# Generated by Django 2.1 on 2018-08-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodels', '0002_auto_20180809_1118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelParams',
            new_name='ModelParam',
        ),
    ]
