# Generated by Django 2.1 on 2018-08-10 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodels', '0003_auto_20180810_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelparam',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_params', to='mlmodels.MLModel'),
        ),
    ]
